name: Scraping and Slack Notification

on:
  schedule:
    - cron: "0 */4 * * *" # 4時間に1回
  workflow_dispatch: # 手動実行用のトリガー

jobs:
  scraping-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Run scraper
        run: node dist/index.js
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
